// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function EnqueueDownload(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EnqueueDownload'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetEnvironment() {
  return window['go']['main']['App']['GetEnvironment']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function InspectURL(arg1) {
  return window['go']['main']['App']['InspectURL'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['main']['App']['RemoveTask'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectCookieFile() {
  return window['go']['main']['App']['SelectCookieFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateEngine() {
  return window['go']['main']['App']['UpdateEngine']();
}
