// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queue} from '../models';
import {config} from '../models';
import {models} from '../models';
import {engine} from '../models';

export function CancelTask(arg1:string):Promise<void>;

export function EnqueueDownload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<queue.Task>;

export function GetEnvironment():Promise<Record<string, any>>;

export function GetSettings():Promise<config.AppSettings>;

export function GetTasks():Promise<Array<queue.Task>>;

export function InspectURL(arg1:string):Promise<models.MediaInfo>;

export function OpenFile(arg1:string):Promise<void>;

export function RemoveTask(arg1:string):Promise<void>;

export function RevealFile(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.AppSettings):Promise<void>;

export function SelectCookieFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function UpdateEngine():Promise<engine.UpdateResult>;
